### ISSUE TITLE
Missing README.md 

### ISSUE THREAD

**Issue by bbulkow** [seenickcode/analytics-go-aerospike-example#1]
Hi Nick, Brian from Aerospike here

Would love to include this project in our partners/examples/cool people page

It's hard to see what this does without a README.md ( I read the code but I don't really get the point )

how about adding one, then people will know what the project does, and we can make noise about it ?

**Comment by seenickcode** [comment]
Hey Brian, good point!  

Problem is that I should take it down and do a proper blog post w/ working example as this was only non-functional code as an addendum to my recent meetup.
